In [2]:
import pandas as pd
import mysql.connector
import json

In [3]:
accounts=pd.read_csv("accounts.csv")
support_tickets=pd.read_csv("support_tickets.csv")
branches=pd.read_csv("branches.csv")
credit_cards=pd.read_json("credit_cards.json")
customers=pd.read_csv("customers.csv")
loans=pd.read_csv("loans.csv")
transactions=pd.read_csv("transactions.csv")

In [18]:
accounts.head()

  customer_id  account_balance         last_updated
0       C0001        293729.87  2025-05-24 09:46:29
1       C0002        150735.15  2025-05-24 09:46:29
2       C0003        170156.21  2025-05-24 09:46:29
3       C0004        311383.96  2025-05-24 09:46:29
4       C0005         60320.75  2025-05-24 09:46:29

In [21]:
accounts.tail()

    customer_id  account_balance         last_updated
495       C0496        149135.80  2025-05-24 09:46:29
496       C0497        376153.36  2025-05-24 09:46:29
497       C0498        320254.17  2025-05-24 09:46:29
498       C0499        484758.19  2025-05-24 09:46:29
499       C0500        454127.94  2025-05-24 09:46:29

In [23]:
accounts.isnull().sum()

customer_id        0
account_balance    0
last_updated       0
dtype: int64

In [44]:
accounts.columns

Index(['customer_id', 'account_balance', 'last_updated'], dtype='str')

In [24]:
accounts.describe()

       account_balance
count       500.000000
mean     246996.117180
std      143128.631994
min        1669.730000
25%      127210.265000
50%      259209.460000
75%      370645.007500
max      498739.490000

In [32]:
accounts.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      500 non-null    str
 1   account_balance  500 non-null    float64
 2   last_updated     500 non-null    str
dtypes: float64(1), str(2)
memory usage: 11.8 KB

In [35]:
accounts.index

RangeIndex(start=0, stop=500, step=1)

In [37]:
type(accounts.columns)

pandas.Index

In [38]:
accounts.dtypes

customer_id            str
account_balance    float64
last_updated           str
dtype: object

In [ ]:
accounts.shape

(500, 3)

In [43]:
accounts.value_counts()

customer_id  account_balance  last_updated
C0001        293729.87        2025-05-24 09:46:29    1
C0002        150735.15        2025-05-24 09:46:29    1
C0003        170156.21        2025-05-24 09:46:29    1
C0004        311383.96        2025-05-24 09:46:29    1
C0005        60320.75         2025-05-24 09:46:29    1
                                                    ..
C0496        149135.80        2025-05-24 09:46:29    1
C0497        376153.36        2025-05-24 09:46:29    1
C0498        320254.17        2025-05-24 09:46:29    1
C0499        484758.19        2025-05-24 09:46:29    1
C0500        454127.94        2025-05-24 09:46:29    1
Name: count, Length: 500, dtype: int64

In [48]:
accounts.sample()

    customer_id  account_balance         last_updated
120       C0121        228279.43  2025-05-24 09:46:29

In [49]:
accounts.sample(n=5)

    customer_id  account_balance         last_updated
70        C0071        312118.71  2025-05-24 09:46:29
210       C0211        418555.16  2025-05-24 09:46:29
442       C0443        390725.38  2025-05-24 09:46:29
250       C0251        155836.17  2025-05-24 09:46:29
397       C0398        221913.57  2025-05-24 09:46:29

In [50]:
accounts.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Length: 500, dtype: bool

In [51]:
accounts.duplicated().sum()

np.int64(0)

In [59]:
accounts["last_updated"].head()

0    2025-05-24 09:46:29
1    2025-05-24 09:46:29
2    2025-05-24 09:46:29
3    2025-05-24 09:46:29
4    2025-05-24 09:46:29
Name: last_updated, dtype: str

In [57]:
accounts["customer_id"].value_counts()

customer_id
C0001    1
C0002    1
C0003    1
C0004    1
C0005    1
        ..
C0496    1
C0497    1
C0498    1
C0499    1
C0500    1
Name: count, Length: 500, dtype: int64

In [61]:
customers.describe()

              age
count  500.000000
mean    44.398000
std     15.255985
min     18.000000
25%     31.000000
50%     45.000000
75%     57.000000
max     70.000000

In [62]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   500 non-null    str
 1   name          500 non-null    str
 2   gender        500 non-null    str
 3   age           500 non-null    int64
 4   city          500 non-null    str
 5   account_type  500 non-null    str
 6   join_date     500 non-null    str
dtypes: int64(1), str(6)
memory usage: 27.5 KB

In [60]:
customers.head()

,customer_id,name,gender,age,city,account_type,join_date
0,C0001,Richard Wilson,M,65,Kimberlyburgh,Savings,2023-08-27
1,C0002,Holly Parker,F,41,Port David,Current,2023-12-08
2,C0003,Megan Alvarez,M,46,West Laurieton,Savings,2022-05-25
3,C0004,Nicholas Stewart,F,39,Amyville,Current,2020-11-30
4,C0005,Douglas Anderson,M,70,New Craigport,Current,2023-01-29

In [73]:
customers.tail()

,customer_id,name,gender,age,city,account_type,join_date
495,C0496,Jennifer Flores,M,50,Mullenland,Savings,2021-04-03
496,C0497,Melissa Martin,M,41,Shermanfurt,Current,2021-12-27
497,C0498,Christopher Johnson,M,69,Nataliemouth,Savings,2022-10-10
498,C0499,Alvin Compton,M,30,Millerstad,Current,2023-06-16
499,C0500,Emily Brooks,M,47,South Louismouth,Savings,2023-10-11

In [74]:
customers["customer_id"].value_counts()

customer_id
C0001    1
C0002    1
C0003    1
C0004    1
C0005    1
        ..
C0496    1
C0497    1
C0498    1
C0499    1
C0500    1
Name: count, Length: 500, dtype: int64

In [75]:
customers["name"].value_counts()

name
Anthony Ross           2
Richard Wilson         1
Holly Parker           1
Megan Alvarez          1
Nicholas Stewart       1
                      ..
Jennifer Flores        1
Melissa Martin         1
Christopher Johnson    1
Alvin Compton          1
Emily Brooks           1
Name: count, Length: 499, dtype: int64

In [64]:
customers["join_date"].head()

0    2023-08-27
1    2023-12-08
2    2022-05-25
3    2020-11-30
4    2023-01-29
Name: join_date, dtype: str

In [65]:
customers.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Length: 500, dtype: bool

In [66]:
customers.duplicated().sum()

np.int64(0)

In [68]:
customers.isnull().sum()

customer_id     0
name            0
gender          0
age             0
city            0
account_type    0
join_date       0
dtype: int64

In [69]:
customers.dtypes

customer_id       str
name              str
gender            str
age             int64
city              str
account_type      str
join_date         str
dtype: object

In [70]:
customers['customer_id'].nunique()

500

In [76]:
customers.dtypes

customer_id                str
name                       str
gender                     str
age                      int64
city                       str
account_type               str
join_date       datetime64[us]
dtype: object

In [77]:
customers.columns

Index(['customer_id', 'name', 'gender', 'age', 'city', 'account_type',
       'join_date'],
      dtype='str')

In [78]:
transactions.describe()

             amount
count  10000.000000
mean   49721.848516
std    29045.696434
min      106.440000
25%    24568.575000
50%    49323.930000
75%    74957.352500
max    99999.050000

In [79]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   txn_id       10000 non-null  str
 1   customer_id  10000 non-null  str
 2   txn_type     10000 non-null  str
 3   amount       10000 non-null  float64
 4   txn_time     10000 non-null  str
 5   status       10000 non-null  str
dtypes: float64(1), str(5)
memory usage: 468.9 KB

In [89]:
transactions.tail()

      txn_id customer_id    txn_type    amount             txn_time   status
9995  T09996       C0260  withdrawal  54743.72  2024-07-28 08:41:01  success
9996  T09997       C0172    purchase  13087.77  2024-06-23 07:24:30   failed
9997  T09998       C0494  withdrawal  66846.76  2025-02-10 01:47:28   failed
9998  T09999       C0499  withdrawal  90759.88  2024-12-11 04:45:07  success
9999  T10000       C0201  withdrawal  92878.32  2024-06-27 18:07:13   failed

In [92]:
transactions["txn_id"].nunique()

10000

In [105]:
transactions["txn_type"].nunique()

5

In [95]:
transactions.isnull().sum()

txn_id         0
customer_id    0
txn_type       0
amount         0
txn_time       0
status         0
dtype: int64

In [98]:
transactions.duplicated().sum()

np.int64(0)

In [82]:
transactions["amount"].max()

np.float64(99999.05)

In [83]:
transactions["amount"].min()

np.float64(106.44)

In [84]:
transactions["amount"].mean()

np.float64(49721.848516000005)

In [85]:
transactions["amount"].median()

np.float64(49323.93)

In [86]:
transactions["amount"].mode()

0    16415.41
1    26749.08
2    26826.58
3    32537.79
4    36468.39
5    67471.47
Name: amount, dtype: float64

In [99]:
transactions["amount"].describe()

count    10000.000000
mean     49721.848516
std      29045.696434
min        106.440000
25%      24568.575000
50%      49323.930000
75%      74957.352500
max      99999.050000
Name: amount, dtype: float64

In [106]:
transactions["amount"].describe()

count    10000.000000
mean     49721.848516
std      29045.696434
min        106.440000
25%      24568.575000
50%      49323.930000
75%      74957.352500
max      99999.050000
Name: amount, dtype: float64

In [108]:
transactions["status"].value_counts()

status
success    8503
failed     1497
Name: count, dtype: int64

In [111]:
suspicious = transactions.groupby(["customer_id", "txn_time"]).size().reset_index(name="count")
suspicious

     customer_id            txn_time  count
0          C0001 2024-05-26 08:20:42      1
1          C0001 2024-05-31 05:26:10      1
2          C0001 2024-06-12 14:15:03      1
3          C0001 2024-06-17 15:46:07      1
4          C0001 2024-06-27 05:32:56      1
...          ...                 ...    ...
9995       C0500 2025-04-19 11:36:47      1
9996       C0500 2025-04-21 05:45:46      1
9997       C0500 2025-05-08 14:01:58      1
9998       C0500 2025-05-11 19:32:53      1
9999       C0500 2025-05-18 05:48:30      1

[10000 rows x 3 columns]

In [112]:
suspicious[suspicious["count"] > 5]

Empty DataFrame
Columns: [customer_id, txn_time, count]
Index: []

In [114]:
avg_amount = transactions.groupby("customer_id")["amount"].transform("mean")
avg_amount

0       47410.313043
1       51736.981579
2       46621.313158
3       46146.320625
4       58447.862000
            ...
9995    49039.902857
9996    49052.903000
9997    58245.250952
9998    53551.580000
9999    41257.761034
Name: amount, Length: 10000, dtype: float64

In [115]:
transactions["sudden_high"] = transactions["amount"] > (avg_amount * 3)
transactions

,txn_id,customer_id,txn_type,amount,txn_time,status,sudden_high
0,T00001,C0363,deposit,44442.71,2025-02-14 06:26:00,success,False
1,T00002,C0432,deposit,15737.59,2025-03-27 07:21:21,success,False
2,T00003,C0084,withdrawal,82150.70,2024-07-31 18:28:06,success,False
3,T00004,C0067,withdrawal,20313.86,2024-11-11 12:18:47,success,False
4,T00005,C0485,withdrawal,74536.08,2025-04-15 10:52:59,success,False
...,...,...,...,...,...,...,...
9995,T09996,C0260,withdrawal,54743.72,2024-07-28 08:41:01,success,False
9996,T09997,C0172,purchase,13087.77,2024-06-23 07:24:30,failed,False
9997,T09998,C0494,withdrawal,66846.76,2025-02-10 01:47:28,failed,False
9998,T09999,C0499,withdrawal,90759.88,2024-12-11 04:45:07,success,False
9999,T10000,C0201,withdrawal,92878.32,2024-06-27 18:07:13,failed,False

In [116]:
loans.describe()

,Loan_ID,Customer_ID,Account_ID,Loan_Amount,Interest_Rate,Loan_Term_Months
count,553.000000,553.000000,553.000000,5.530000e+02,553.000000,553.000000
mean,277.000000,1305.819168,2318.987342,2.472737e+06,10.528933,98.213382
std,159.781622,170.117382,171.044134,1.410436e+06,2.381320,75.903577
min,1.000000,1002.000000,2004.000000,5.965500e+04,6.500000,12.000000
25%,139.000000,1162.000000,2175.000000,1.223813e+06,8.380000,36.000000
50%,277.000000,1309.000000,2313.000000,2.481325e+06,10.490000,84.000000
75%,415.000000,1454.000000,2478.000000,3.662862e+06,12.610000,180.000000
max,553.000000,1598.000000,2598.000000,4.996702e+06,14.480000,240.000000

In [117]:
loans.info()

<class 'pandas.DataFrame'>
RangeIndex: 553 entries, 0 to 552
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Loan_ID           553 non-null    int64
 1   Customer_ID       553 non-null    int64
 2   Account_ID        553 non-null    int64
 3   Branch            553 non-null    str
 4   Loan_Type         553 non-null    str
 5   Loan_Amount       553 non-null    int64
 6   Interest_Rate     553 non-null    float64
 7   Loan_Term_Months  553 non-null    int64
 8   Start_Date        553 non-null    str
 9   End_Date          553 non-null    str
 10  Loan_Status       553 non-null    str
dtypes: float64(1), int64(5), str(5)
memory usage: 47.7 KB

In [118]:
loans.head()

,Loan_ID,Customer_ID,Account_ID,Branch,Loan_Type,Loan_Amount,Interest_Rate,Loan_Term_Months,Start_Date,End_Date,Loan_Status
0,1,1559,2090,Perez Ltd Branch,Personal,259805,12.43,60,2017-07-03,2022-06-07,Active
1,2,1028,2575,Harris-Marshall Branch,Business,3589336,6.75,24,2017-06-14,2019-06-04,Active
2,3,1164,2433,"Taylor, David and Brown Branch",Auto,4621300,9.86,240,2021-08-10,2041-04-27,Closed
3,4,1100,2368,Robertson and Sons Branch,Home,2380953,7.74,120,2016-02-23,2026-01-01,Approved
4,5,1081,2566,"Parrish, Hall and Adams Branch",Home,2268961,12.96,240,2021-01-05,2040-09-22,Approved

In [119]:
loans.tail()

,Loan_ID,Customer_ID,Account_ID,Branch,Loan_Type,Loan_Amount,Interest_Rate,Loan_Term_Months,Start_Date,End_Date,Loan_Status
548,549,1534,2214,"Potts, Gutierrez and Hancock Branch",Education,2123346,12.40,12,2017-03-26,2018-03-21,Defaulted
549,550,1563,2534,"Cunningham, Lee and Fleming Branch",Education,3314199,11.95,84,2018-08-16,2025-07-10,Active
550,551,1224,2116,Richardson-Morales Branch,Personal,2174941,10.35,84,2017-03-24,2024-02-16,Closed
551,552,1406,2249,"Ross, Hayes and Erickson Branch",Auto,3692011,9.10,36,2023-11-28,2026-11-12,Closed
552,553,1092,2255,"Stewart, Wilson and Dalton Branch",Personal,402265,11.15,240,2022-09-20,2042-06-07,Active

In [121]:
loans.isnull().sum()

Loan_ID             0
Customer_ID         0
Account_ID          0
Branch              0
Loan_Type           0
Loan_Amount         0
Interest_Rate       0
Loan_Term_Months    0
Start_Date          0
End_Date            0
Loan_Status         0
dtype: int64

In [123]:
loans.duplicated().sum()

np.int64(0)

In [125]:
loans.dtypes

Loan_ID               int64
Customer_ID           int64
Account_ID            int64
Branch                  str
Loan_Type               str
Loan_Amount           int64
Interest_Rate       float64
Loan_Term_Months      int64
Start_Date              str
End_Date                str
Loan_Status             str
dtype: object

In [127]:
loans.columns

Index(['Loan_ID', 'Customer_ID', 'Account_ID', 'Branch', 'Loan_Type',
       'Loan_Amount', 'Interest_Rate', 'Loan_Term_Months', 'Start_Date',
       'End_Date', 'Loan_Status'],
      dtype='str')

In [129]:
loans["Loan_ID"].value_counts()

Loan_ID
1      1
2      1
3      1
4      1
5      1
      ..
549    1
550    1
551    1
552    1
553    1
Name: count, Length: 553, dtype: int64

In [132]:
loans["Loan_Amount"].describe()

count    5.530000e+02
mean     2.472737e+06
std      1.410436e+06
min      5.965500e+04
25%      1.223813e+06
50%      2.481325e+06
75%      3.662862e+06
max      4.996702e+06
Name: Loan_Amount, dtype: float64

In [134]:
loans["Interest_Rate"].describe()

count    553.000000
mean      10.528933
std        2.381320
min        6.500000
25%        8.380000
50%       10.490000
75%       12.610000
max       14.480000
Name: Interest_Rate, dtype: float64

In [136]:
loans["Loan_Status"].value_counts()

Loan_Status
Active       143
Approved     142
Defaulted    138
Closed       130
Name: count, dtype: int64

In [138]:
branches.describe()

        Branch_ID  Total_Employees  Branch_Revenue  Performance_Rating
count  520.000000       520.000000    5.200000e+02          520.000000
mean   260.500000       107.442308    1.040475e+07            2.959615
std    150.255338        54.393419    5.625453e+06            1.443978
min      1.000000        15.000000    5.033894e+05            1.000000
25%    130.750000        62.000000    5.782829e+06            2.000000
50%    260.500000       108.500000    1.030429e+07            3.000000
75%    390.250000       152.250000    1.561868e+07            4.000000
max    520.000000       200.000000    1.990557e+07            5.000000

In [139]:
branches.info()

<class 'pandas.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Branch_ID           520 non-null    int64
 1   Branch_Name         520 non-null    str
 2   City                520 non-null    str
 3   Manager_Name        520 non-null    str
 4   Total_Employees     520 non-null    int64
 5   Branch_Revenue      520 non-null    float64
 6   Opening_Date        520 non-null    str
 7   Performance_Rating  520 non-null    int64
dtypes: float64(1), int64(3), str(4)
memory usage: 32.6 KB

In [140]:
branches.head()

,Branch_ID,Branch_Name,City,Manager_Name,Total_Employees,Branch_Revenue,Opening_Date,Performance_Rating
0,1,"Wang, Mcdonald and Church Branch",Kellitown,Kevin Jones,141,16849288.09,2008-08-01,2
1,2,Crawford-Torres Branch,Angelaburgh,Andrea Steele,39,5822279.32,2015-09-17,1
2,3,Bridges Inc Branch,Johnsonfort,Michael Coleman,195,2114594.03,2012-07-30,3
3,4,Garcia Group Branch,New Kyleberg,Dawn Cooper,144,3390389.63,2018-06-27,2
4,5,"Arroyo, Moore and Freeman Branch",West Coryborough,Samantha Kennedy,42,2771910.11,2012-01-04,5

In [141]:
branches.tail()

,Branch_ID,Branch_Name,City,Manager_Name,Total_Employees,Branch_Revenue,Opening_Date,Performance_Rating
515,516,Lowery and Sons Branch,Lake Charles,Daniel Hunt,130,6562890.41,2007-06-22,4
516,517,Brooks Group Branch,New Christina,Rodney Browning,19,19078758.01,2021-07-20,1
517,518,Harris-Marshall Branch,Emilymouth,Lorraine Johnson,177,2801634.32,2011-08-18,5
518,519,"Meadows, Taylor and Butler Branch",Port Michael,David Smith,76,17653138.31,2006-05-21,4
519,520,Beltran-Nelson Branch,Juliabury,Richard Singleton,171,19520645.33,2010-09-13,1

In [143]:
branches.isnull().sum()

Branch_ID             0
Branch_Name           0
City                  0
Manager_Name          0
Total_Employees       0
Branch_Revenue        0
Opening_Date          0
Performance_Rating    0
dtype: int64

In [145]:
branches.duplicated().sum()

np.int64(0)

In [149]:
branches["Branch_ID"].value_counts()

Branch_ID
1      1
2      1
3      1
4      1
5      1
      ..
516    1
517    1
518    1
519    1
520    1
Name: count, Length: 520, dtype: int64

In [150]:
branches["Branch_ID"].nunique()

520

In [147]:
branches.columns

Index(['Branch_ID', 'Branch_Name', 'City', 'Manager_Name', 'Total_Employees',
       'Branch_Revenue', 'Opening_Date', 'Performance_Rating'],
      dtype='str')

In [148]:
branches.dtypes

Branch_ID               int64
Branch_Name               str
City                      str
Manager_Name              str
Total_Employees         int64
Branch_Revenue        float64
Opening_Date              str
Performance_Rating      int64
dtype: object

In [151]:
support_tickets.describe()

          Loan_ID  Customer_Rating
count  229.000000       600.000000
mean   300.480349         3.011667
std    165.450305         1.402906
min      1.000000         1.000000
25%    153.000000         2.000000
50%    339.000000         3.000000
75%    442.000000         4.000000
max    553.000000         5.000000

In [152]:
support_tickets.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Ticket_ID           600 non-null    str
 1   Customer_ID         600 non-null    str
 2   Account_ID          600 non-null    str
 3   Loan_ID             229 non-null    float64
 4   Branch_Name         600 non-null    str
 5   Issue_Category      600 non-null    str
 6   Description         600 non-null    str
 7   Date_Opened         600 non-null    str
 8   Date_Closed         496 non-null    str
 9   Priority            600 non-null    str
 10  Status              600 non-null    str
 11  Resolution_Remarks  600 non-null    str
 12  Support_Agent       600 non-null    str
 13  Channel             600 non-null    str
 14  Customer_Rating     600 non-null    int64
dtypes: float64(1), int64(1), str(13)
memory usage: 70.4 KB

In [154]:
support_tickets.isnull().sum()

Ticket_ID               0
Customer_ID             0
Account_ID              0
Loan_ID               371
Branch_Name             0
Issue_Category          0
Description             0
Date_Opened             0
Date_Closed           104
Priority                0
Status                  0
Resolution_Remarks      0
Support_Agent           0
Channel                 0
Customer_Rating         0
dtype: int64

In [173]:
support_tickets.columns

Index(['Ticket_ID', 'Customer_ID', 'Account_ID', 'Loan_ID', 'Branch_Name',
       'Issue_Category', 'Description', 'Date_Opened', 'Date_Closed',
       'Priority', 'Status', 'Resolution_Remarks', 'Support_Agent', 'Channel',
       'Customer_Rating'],
      dtype='str')

In [156]:
support_tickets.duplicated().sum()

np.int64(0)

In [158]:
support_tickets.columns

Index(['Ticket_ID', 'Customer_ID', 'Account_ID', 'Loan_ID', 'Branch_Name',
       'Issue_Category', 'Description', 'Date_Opened', 'Date_Closed',
       'Priority', 'Status', 'Resolution_Remarks', 'Support_Agent', 'Channel',
       'Customer_Rating'],
      dtype='str')

In [174]:
support_tickets.head()

,Ticket_ID,Customer_ID,Account_ID,Loan_ID,Branch_Name,Issue_Category,Description,Date_Opened,Date_Closed,Priority,Status,Resolution_Remarks,Support_Agent,Channel,Customer_Rating
0,T00001,C0478,A1825,NaN,Gonzalez-Martin Branch,Loan Payment Delay,Client raised loan payment delay.,2017-09-30,2017-10-24,Low,Closed,Card replaced and activated.,Leena Apte,Email,1
1,T00002,C0443,A3583,NaN,Baldwin and Sons Branch,Loan Foreclosure,Client raised loan foreclosure.,2015-04-19,2015-05-12,Critical,In Progress,Card replaced and activated.,Owen Mahajan,In-person,1
2,T00003,C0057,A2616,442.0,"Porter, Osborne and Mendez Branch",Interest Rate Dispute,Customer reported interest rate dispute.,2016-09-28,2016-10-23,High,Resolved,Loan schedule updated.,Wishi Chhabra,Email,4
3,T00004,C0301,A8786,NaN,"Stafford, Oneal and Williams Branch",Mismatch in Account Statement,Client raised mismatch in account statement.,2019-03-31,2019-04-10,High,Closed,Pending customer verification.,Gabriel Mutti,Email,1
4,T00005,C0238,A3734,NaN,Evans-Mercado Branch,KYC Update Required,System detected kyc update required.,2017-08-11,NaN,Critical,Resolved,Pending customer verification.,Ekani Oza,In-person,2

In [175]:
support_tickets.tail()

,Ticket_ID,Customer_ID,Account_ID,Loan_ID,Branch_Name,Issue_Category,Description,Date_Opened,Date_Closed,Priority,Status,Resolution_Remarks,Support_Agent,Channel,Customer_Rating
595,T00596,C0303,A9594,NaN,Johnson Group Branch,Account Frozen,Customer reported account frozen.,2015-03-08,2015-03-30,Medium,Escalated,Issue resolved successfully.,Chaitaly Vaidya,Mobile App,3
596,T00597,C0480,A5144,NaN,Clark Inc Branch,Interest Rate Dispute,Customer reported interest rate dispute.,2020-01-17,2020-01-26,Medium,In Progress,Issue resolved successfully.,Ekapad Jhaveri,In-person,1
597,T00598,C0270,A7108,427.0,Murphy-Johnston Branch,Interest Rate Dispute,Client raised interest rate dispute.,2016-04-22,2016-05-13,Critical,Resolved,Loan schedule updated.,Advik Bhagat,In-person,4
598,T00599,C0144,A4959,121.0,"Herrera, Rollins and Hill Branch",Card Not Working,Customer reported card not working.,2015-02-26,2015-03-25,Low,In Progress,Card replaced and activated.,Wriddhish Sarraf,Phone,2
599,T00600,C0076,A7140,24.0,Peterson-Graves Branch,EMI Auto-debit Failed,Customer reported emi auto-debit failed.,2023-08-19,2023-09-04,Critical,Escalated,Card replaced and activated.,Ria Ghose,Mobile App,5

In [160]:
support_tickets.dtypes

Ticket_ID                 str
Customer_ID               str
Account_ID                str
Loan_ID               float64
Branch_Name               str
Issue_Category            str
Description               str
Date_Opened               str
Date_Closed               str
Priority                  str
Status                    str
Resolution_Remarks        str
Support_Agent             str
Channel                   str
Customer_Rating         int64
dtype: object

In [161]:
support_tickets["Ticket_ID"].value_counts()

Ticket_ID
T00001    1
T00002    1
T00003    1
T00004    1
T00005    1
         ..
T00596    1
T00597    1
T00598    1
T00599    1
T00600    1
Name: count, Length: 600, dtype: int64

In [162]:
support_tickets["Status"].value_counts()

Status
Closed         128
In Progress    122
Escalated      121
Open           119
Resolved       110
Name: count, dtype: int64

In [163]:
support_tickets[support_tickets["Date_Closed"] < support_tickets["Date_Opened"]]

Empty DataFrame
Columns: [Ticket_ID, Customer_ID, Account_ID, Loan_ID, Branch_Name, Issue_Category, Description, Date_Opened, Date_Closed, Priority, Status, Resolution_Remarks, Support_Agent, Channel, Customer_Rating]
Index: []

In [166]:
support_tickets["Customer_ID"].value_counts()

Customer_ID
C0378    6
C0129    6
C0341    6
C0221    5
C0437    5
        ..
C0468    1
C0302    1
C0480    1
C0144    1
C0076    1
Name: count, Length: 366, dtype: int64

In [167]:
support_tickets["Ticket_ID"].duplicated().sum()

np.int64(0)

In [169]:
support_tickets["Customer_ID"].value_counts()

Customer_ID
C0378    6
C0129    6
C0341    6
C0221    5
C0437    5
        ..
C0468    1
C0302    1
C0480    1
C0144    1
C0076    1
Name: count, Length: 366, dtype: int64

In [171]:
support_tickets.isnull().sum()

Ticket_ID               0
Customer_ID             0
Account_ID              0
Loan_ID               371
Branch_Name             0
Issue_Category          0
Description             0
Date_Opened             0
Date_Closed           104
Priority                0
Status                  0
Resolution_Remarks      0
Support_Agent           0
Channel                 0
Customer_Rating         0
dtype: int64

In [134]:
support_tickets["Loan_ID"].isnull().sum()

np.int64(371)

In [4]:
support_tickets = support_tickets.where(pd.notnull(support_tickets), None)

In [178]:
support_tickets_null = support_tickets[support_tickets["Loan_ID"].isnull()]
support_tickets_null.head()

,Ticket_ID,Customer_ID,Account_ID,Loan_ID,Branch_Name,Issue_Category,Description,Date_Opened,Date_Closed,Priority,Status,Resolution_Remarks,Support_Agent,Channel,Customer_Rating
0,T00001,C0478,A1825,NaN,Gonzalez-Martin Branch,Loan Payment Delay,Client raised loan payment delay.,2017-09-30,2017-10-24,Low,Closed,Card replaced and activated.,Leena Apte,Email,1
1,T00002,C0443,A3583,NaN,Baldwin and Sons Branch,Loan Foreclosure,Client raised loan foreclosure.,2015-04-19,2015-05-12,Critical,In Progress,Card replaced and activated.,Owen Mahajan,In-person,1
3,T00004,C0301,A8786,NaN,"Stafford, Oneal and Williams Branch",Mismatch in Account Statement,Client raised mismatch in account statement.,2019-03-31,2019-04-10,High,Closed,Pending customer verification.,Gabriel Mutti,Email,1
4,T00005,C0238,A3734,NaN,Evans-Mercado Branch,KYC Update Required,System detected kyc update required.,2017-08-11,NaN,Critical,Resolved,Pending customer verification.,Ekani Oza,In-person,2
5,T00006,C0223,A4375,NaN,Duncan Group Branch,Unauthorized Transaction,System detected unauthorized transaction.,2016-12-01,2016-12-09,Critical,Resolved,KYC documents verified.,Gabriel Mutti,Phone,3

In [5]:
support_tickets["Loan_ID"] = support_tickets["Loan_ID"].fillna("L" + support_tickets.index.astype(str))

TypeError: "value" parameter must be a scalar, dict or Series, but you passed a "Index"

In [6]:
support_tickets["Loan_ID"] = support_tickets["Loan_ID"].fillna(
    "L" + support_tickets.index.to_series().astype(str))
support_tickets["Loan_ID"]

0         L0
1         L1
2      442.0
3         L3
4         L4
       ...
595     L595
596     L596
597    427.0
598    121.0
599     24.0
Name: Loan_ID, Length: 600, dtype: object

In [189]:
support_tickets["Issue_Category"].value_counts()

Issue_Category
Interest Rate Dispute            74
Loan Foreclosure                 72
Loan Payment Delay               66
EMI Auto-debit Failed            53
Mismatch in Account Statement    37
KYC Update Required              36
Account Closure Request          35
Account Access Issue             33
Account Frozen                   32
UPI Payment Failed               31
Debit Card Delivery Delay        30
Unauthorized Transaction         28
Cheque Bounce                    28
Online Transfer Failed           25
Card Not Working                 20
Name: count, dtype: int64

In [191]:
support_tickets["Loan_ID"].isnull().sum()

np.int64(0)

In [192]:
support_tickets["Loan_ID"].duplicated().sum()

np.int64(54)

In [194]:
support_tickets["Ticket_ID"].duplicated().sum()

np.int64(0)

In [195]:
support_tickets["Loan_ID"].value_counts().head()

Loan_ID
119.0    4
370.0    4
211.0    3
297.0    3
234.0    3
Name: count, dtype: int64

In [197]:
support_tickets["Customer_ID"].value_counts().head()

Customer_ID
C0378    6
C0129    6
C0341    6
C0221    5
C0437    5
Name: count, dtype: int64

In [198]:
support_tickets["Issue_Category"].value_counts()

Issue_Category
Interest Rate Dispute            74
Loan Foreclosure                 72
Loan Payment Delay               66
EMI Auto-debit Failed            53
Mismatch in Account Statement    37
KYC Update Required              36
Account Closure Request          35
Account Access Issue             33
Account Frozen                   32
UPI Payment Failed               31
Debit Card Delivery Delay        30
Unauthorized Transaction         28
Cheque Bounce                    28
Online Transfer Failed           25
Card Not Working                 20
Name: count, dtype: int64

In [199]:
credit_cards.describe()

,Card_ID,Customer_ID,Account_ID,Card_Number,Credit_Limit,Current_Balance
count,557.000000,557.000000,557.000000,5.570000e+02,557.000000,557.000000
mean,279.000000,1300.897666,2305.754039,4.913130e+15,281186.197487,136348.971041
std,160.936323,173.373153,173.773220,1.150928e+15,128098.769524,105127.796486
min,1.000000,1002.000000,2001.000000,3.000390e+15,51296.000000,71.990000
25%,140.000000,1152.000000,2149.000000,3.904634e+15,173812.000000,47863.980000
50%,279.000000,1303.000000,2308.000000,4.822750e+15,291209.000000,110095.690000
75%,418.000000,1455.000000,2455.000000,5.902611e+15,388465.000000,198276.110000
max,557.000000,1599.000000,2600.000000,6.983735e+15,499117.000000,476781.040000

In [200]:
credit_cards.info()

<class 'pandas.DataFrame'>
RangeIndex: 557 entries, 0 to 556
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Card_ID          557 non-null    int64
 1   Customer_ID      557 non-null    int64
 2   Account_ID       557 non-null    int64
 3   Branch           557 non-null    str
 4   Card_Number      557 non-null    int64
 5   Card_Type        557 non-null    str
 6   Card_Network     557 non-null    str
 7   Credit_Limit     557 non-null    int64
 8   Current_Balance  557 non-null    float64
 9   Issued_Date      557 non-null    str
 10  Expiry_Date      557 non-null    str
 11  Status           557 non-null    str
dtypes: float64(1), int64(5), str(6)
memory usage: 52.3 KB

In [201]:
credit_cards.isnull().sum()

Card_ID            0
Customer_ID        0
Account_ID         0
Branch             0
Card_Number        0
Card_Type          0
Card_Network       0
Credit_Limit       0
Current_Balance    0
Issued_Date        0
Expiry_Date        0
Status             0
dtype: int64

In [203]:
credit_cards.duplicated().sum()

np.int64(0)

In [206]:
credit_cards.columns

Index(['Card_ID', 'Customer_ID', 'Account_ID', 'Branch', 'Card_Number',
       'Card_Type', 'Card_Network', 'Credit_Limit', 'Current_Balance',
       'Issued_Date', 'Expiry_Date', 'Status'],
      dtype='str')

In [207]:
credit_cards.head()

,Card_ID,Customer_ID,Account_ID,Branch,Card_Number,Card_Type,Card_Network,Credit_Limit,Current_Balance,Issued_Date,Expiry_Date,Status
0,1,1559,2090,Perez Ltd Branch,4960013389083863,Business,Visa,178393,39819.23,2015-04-13,2019-10-27,Expired
1,2,1160,2221,Miller Inc Branch,6511615594078161,Platinum,RuPay,416026,175818.58,2015-01-27,2018-12-18,Expired
2,3,1297,2082,"Miles, Patterson and Murray Branch",6316475255341928,Gold,RuPay,419398,29171.29,2021-06-22,2025-07-19,Active
3,4,1333,2058,"Shepard, Gonzales and Cooper Branch",3305641395376724,Gold,Amex,385544,265316.71,2019-04-04,2023-10-07,Active
4,5,1371,2225,Wilson PLC Branch,6287101226916697,Platinum,RuPay,274622,246561.92,2023-05-18,2029-08-26,Expired

In [208]:
credit_cards.tail()

,Card_ID,Customer_ID,Account_ID,Branch,Card_Number,Card_Type,Card_Network,Credit_Limit,Current_Balance,Issued_Date,Expiry_Date,Status
552,553,1160,2599,"Huff, Bryant and Thomas Branch",6295966048736826,Silver,RuPay,286715,193389.66,2023-06-03,2028-03-08,Active
553,554,1163,2411,Morris-Prince Branch,3865369455158886,Gold,Amex,108003,61642.17,2017-06-13,2021-08-18,Blocked
554,555,1161,2182,"Robertson, Moore and Howell Branch",3640857216966630,Gold,Amex,200094,165305.34,2023-06-27,2029-01-31,Active
555,556,1333,2256,Green-Keith Branch,4297150968832753,Gold,Visa,433856,177349.60,2021-09-21,2027-12-02,Blocked
556,557,1212,2592,"Holmes, Nguyen and French Branch",5773973278195237,Silver,MasterCard,203606,13196.28,2018-08-14,2022-05-11,Active

In [218]:
credit_cards.dtypes

Card_ID                     int64
Customer_ID                 int64
Account_ID                  int64
Branch                        str
Card_Number                   str
Card_Type                     str
Card_Network                  str
Credit_Limit                int64
Current_Balance           float64
Issued_Date        datetime64[us]
Expiry_Date        datetime64[us]
Status                        str
dtype: object

In [211]:
credit_cards["Card_Number"] = credit_cards["Card_Number"].astype(str)
credit_cards["Card_Number"]

0      4960013389083863
1      6511615594078161
2      6316475255341928
3      3305641395376724
4      6287101226916697
             ...
552    6295966048736826
553    3865369455158886
554    3640857216966630
555    4297150968832753
556    5773973278195237
Name: Card_Number, Length: 557, dtype: str

In [214]:
credit_cards["Issued_Date"] = pd.to_datetime(credit_cards["Issued_Date"])
credit_cards["Issued_Date"]

0     2015-04-13
1     2015-01-27
2     2021-06-22
3     2019-04-04
4     2023-05-18
         ...
552   2023-06-03
553   2017-06-13
554   2023-06-27
555   2021-09-21
556   2018-08-14
Name: Issued_Date, Length: 557, dtype: datetime64[us]

In [6]:
credit_cards["Expiry_Date"] = pd.to_datetime(credit_cards["Expiry_Date"])
credit_cards["Expiry_Date"]

0     2019-10-27
1     2018-12-18
2     2025-07-19
3     2023-10-07
4     2029-08-26
         ...
552   2028-03-08
553   2021-08-18
554   2029-01-31
555   2027-12-02
556   2022-05-11
Name: Expiry_Date, Length: 557, dtype: datetime64[us]

In [26]:
conn=mysql.connector.connect(
host="localhost",
user="root",
password="Thirumala@205",
database="customers_data")


cursor=conn.cursor()

In [27]:
cursor.execute("CREATE DATABASE IF NOT EXISTS customers_data")
print("Database created or already exists")

Database created or already exists

In [34]:
customers.columns

Index(['customer_id', 'name', 'gender', 'age', 'city', 'account_type',
       'join_date'],
      dtype='str')

In [52]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS customers(
    customer_id varchar(50) PRIMARY KEY,
    name varchar(50),
    gender char(1),
    age int,
    city varchar(50),
    account_type varchar(20),
    join_date date)""")

In [53]:
for _, row in customers.iterrows():
    cursor.execute("""
            INSERT INTO customers (customer_id,name,gender,age,city,account_type,join_date)values(%s,%s,%s,%s,%s,%s,%s)
                   """,(row['customer_id'],row['name'],row['gender'],row['age'],row['city'],row['account_type'],row['join_date']))

In [59]:
conn.commit()

In [60]:
accounts.columns

Index(['customer_id', 'account_balance', 'last_updated'], dtype='str')

In [61]:
cursor.execute("CREATE DATABASE IF NOT EXISTS accounts_data")
print("Database created or already exists")

Database created or already exists

In [64]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS accounts(
    customer_id varchar(50) PRIMARY KEY,
    account_balance DECIMAL(10,2),
    last_updated DATETIME)""")

In [65]:
for _, row in accounts.iterrows():
    cursor.execute("""
            INSERT INTO accounts (customer_id,account_balance,last_updated)values(%s,%s,%s)
                   """,(row['customer_id'],row['account_balance'],row['last_updated']))

In [66]:
conn.commit()

In [67]:
transactions.columns

Index(['txn_id', 'customer_id', 'txn_type', 'amount', 'txn_time', 'status'], dtype='str')

In [68]:
cursor.execute("CREATE DATABASE IF NOT EXISTS transactions_data")
print("Database created or already exists")

Database created or already exists

In [69]:
transactions.dtypes

txn_id             str
customer_id        str
txn_type           str
amount         float64
txn_time           str
status             str
dtype: object

In [71]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS transactions(
    txn_id INT AUTO_INCREMENT PRIMARY KEY,
    customer_id varchar(50),
    txn_type varchar(20),
    amount decimal,
    txn_time datetime,
    status varchar(20))""")

In [73]:
cursor.execute("""
ALTER TABLE transactions
MODIFY txn_id VARCHAR(20)
""")

In [74]:
for _, row in transactions.iterrows():
    cursor.execute("""
            INSERT INTO transactions (txn_id, customer_id,txn_type,amount,txn_time,status)values(%s,%s,%s,%s,%s,%s)
                   """,(row['txn_id'],row['customer_id'],row['txn_type'],row['amount'],row['txn_time'],row['status']))
    
    conn.commit()

In [79]:
loans.columns

Index(['Loan_ID', 'Customer_ID', 'Account_ID', 'Branch', 'Loan_Type',
       'Loan_Amount', 'Interest_Rate', 'Loan_Term_Months', 'Start_Date',
       'End_Date', 'Loan_Status'],
      dtype='str')

In [81]:
loans.dtypes

Loan_ID               int64
Customer_ID           int64
Account_ID            int64
Branch                  str
Loan_Type               str
Loan_Amount           int64
Interest_Rate       float64
Loan_Term_Months      int64
Start_Date              str
End_Date                str
Loan_Status             str
dtype: object

In [92]:
cursor.execute("CREATE DATABASE IF NOT EXISTS loans_data")
print("Database created or already exists")

Database created or already exists

In [93]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS loans(
    Loan_ID int(20) PRIMARY KEY,
    Customer_ID int(20),
    Account_ID int(20),
    Branch varchar(50),
    Loan_Type varchar(50),
    Loan_Amount int(20),
    Interest_Rate float,
    Loan_Term_Months int(20),    
    Start_Date DATETIME,
    End_Date DATETIME,
    Loan_Status varchar(50))""")

In [95]:
for _, row in loans.iterrows():
    cursor.execute("""
            INSERT INTO loans (Loan_ID, Customer_ID,Account_ID,Branch,Loan_Type,Loan_Amount,Interest_Rate,Loan_Term_Months,Start_Date,End_Date,Loan_Status)values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
                   """,(row['Loan_ID'],row['Customer_ID'],row['Account_ID'],row['Branch'],row['Loan_Type'],row['Loan_Amount'],row['Interest_Rate'],row['Loan_Term_Months'],row['Start_Date'],row['End_Date'],row['Loan_Status']))
    
    conn.commit()

In [96]:
branches.columns

Index(['Branch_ID', 'Branch_Name', 'City', 'Manager_Name', 'Total_Employees',
       'Branch_Revenue', 'Opening_Date', 'Performance_Rating'],
      dtype='str')

In [98]:
branches.dtypes

Branch_ID               int64
Branch_Name               str
City                      str
Manager_Name              str
Total_Employees         int64
Branch_Revenue        float64
Opening_Date              str
Performance_Rating      int64
dtype: object

In [97]:
cursor.execute("CREATE DATABASE IF NOT EXISTS branches_data")
print("Database created or already exists")

Database created or already exists

In [103]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS branches(
    Branch_ID int(20),
    Branch_Name varchar(50),
    City varchar(50),
    Manager_Name varchar(50),
    Total_Employees int(20),
    Branch_Revenue float,
    Opening_Date DATETIME,
    Performance_Rating int(20)   
    )""")

In [111]:
for _, row in branches.iterrows():
    cursor.execute("""
            INSERT INTO branches (Branch_ID, Branch_Name,City,Manager_Name,Total_Employees, Branch_Revenue,Opening_Date,Performance_Rating)values(%s,%s,%s,%s,%s,%s,%s,%s)
                   """,(row['Branch_ID'],row['Branch_Name'],row['City'],row['Manager_Name'],row['Total_Employees'],row['Branch_Revenue'],row['Opening_Date'],row['Performance_Rating']))
    
    conn.commit()

In [112]:
support_tickets.columns

Index(['Ticket_ID', 'Customer_ID', 'Account_ID', 'Loan_ID', 'Branch_Name',
       'Issue_Category', 'Description', 'Date_Opened', 'Date_Closed',
       'Priority', 'Status', 'Resolution_Remarks', 'Support_Agent', 'Channel',
       'Customer_Rating'],
      dtype='str')

In [113]:
support_tickets.dtypes

Ticket_ID                 str
Customer_ID               str
Account_ID                str
Loan_ID               float64
Branch_Name               str
Issue_Category            str
Description               str
Date_Opened               str
Date_Closed               str
Priority                  str
Status                    str
Resolution_Remarks        str
Support_Agent             str
Channel                   str
Customer_Rating         int64
dtype: object

In [128]:
cursor.execute("CREATE DATABASE IF NOT EXISTS support_tickets_data")
print("Database created or already exists")

Database created or already exists

In [127]:
cursor.execute("DROP TABLE IF EXISTS support_tickets")

In [129]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS support_tickets(
    Ticket_ID varchar(50),
    Customer_ID  varchar(50),
    Account_ID varchar(50),
    Loan_ID float,
    Branch_Name varchar(50),
    Issue_Category varchar(50),
    Description varchar(50),
    Date_Opened DATETIME,
    Date_Closed DATETIME,
    Priority varchar(50),
    Status varchar(50),
    Resolution_Remarks varchar(50),
    Support_Agent varchar(50),
    Channel varchar(50),
    Customer_Rating int(20) )""")

In [136]:
for _, row in support_tickets.iterrows():
    cursor.execute("""
            INSERT INTO support_tickets(Ticket_ID, Customer_ID,Account_ID,Loan_ID,Branch_Name,Issue_Category,Description,Date_Opened,Date_Closed,Priority,Status,Resolution_Remarks,Support_Agent,Channel,Customer_Rating)values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
                   """,(row['Ticket_ID'],row['Customer_ID'],row['Account_ID'],row['Loan_ID'],row['Branch_Name'],row['Issue_Category'],row['Description'],row['Date_Opened'],row['Date_Closed'],row['Priority'],row['Status'],row['Resolution_Remarks'],row['Support_Agent'],row['Channel'],row['Customer_Rating']))
    
    conn.commit()

ProgrammingError: 1054 (42S22): Unknown column 'nan' in 'field list'

In [ ]:
#sample
"""select c.city,a.account_balance from customers as c join accounts as a on c.customer_id=a.customer_id;"""

'select c.city,a.account_balance from customers as c join accounts as a on c.customer_id=a.customer_id;'

In [76]:
# How many customers exist per city, and what is their average account balance?
"""select c.city,count(distinct c.customer_id),avg(a.account_balance) as avg_balance from customers as c join accounts as a on c.customer_id=a.customer_id GROUP BY c.city;"""

'select c.city,count(distinct c.customer_id),avg(a.account_balance) as avg_balance from customers as c join accounts as a on c.customer_id=a.customer_id GROUP BY c.city;'

In [78]:
#Q2: Which account type (Savings, Current, Loan, etc.) holds the highest total balance?
"""select c.account_type, sum(a.account_balance) from customers c join accounts a on c.customer_id=a.customer_id GROUP BY account_type;"""

'select c.account_type, sum(a.account_balance) from customers c join accounts a on c.customer_id=a.customer_id GROUP BY account_type;'

In [ ]:
#Q3: Who are the top 10 customers by total account balance across all account types?
select c.customer_id,c.name, sum(a.account_balance) from customers c join accounts a on c.customer_id=a.customer_id GROUP BY c.customer_id,c.name order by account_balance DESC LIMIT 10;

In [ ]:
#Q4: Which customers opened accounts in 2023 with a balance above ₹1,00,000?
select account_balance,last_updated from accounts where account_balance>100000 and last_updated between '2023-01-01 00:00:00' and '2023-12-311 00:00:00'

In [ ]:
#Q5: What is the total transaction volume (sum of amounts) by transaction type?
select txn_type, sum(amount) from transactions GROUP BY txn_type;

In [ ]:
#Q6: How many failed transactions occurred for each transaction type?
select count(*) as failed_transactions,txn_type from transactions where status='failed' Group By txn_type;

In [ ]:
#Q7: What is the total number of transactions per transaction type?
select count(*) as total_transactions,txn_type from transactions GROUP BY txn_type;

In [ ]:
#Q8: Which accounts have 5 or more high-value transactions above ₹20,000?
SELECT customer_id, COUNT(*) AS high_value_txns FROM transactions WHERE amount > 20000 GROUP BY customer_id HAVING COUNT(*) >= 5;

In [ ]:
#Q9: What is the average loan amount and interest rate by loan type (Personal, Auto, Home, etc.)?
SELECT Loan_Type, AVG(Loan_Amount), AVG(Interest_Rate) FROM loans GROUP BY Loan_Type;

In [ ]:
#Q10: Which customers currently hold more than one active or approved loan?

In [ ]:
#Who are the top 5 customers with the highest outstanding (non-closed) loan amounts?